[package]
name = "moxidle"
version = "0.1.0"
edition = "2021"

[dependencies]
calloop = { version = "0.14.2", features = [ "executor" ] }
calloop-wayland-source = "0.4.0"
env_logger = "0.11.6"
log = "0.4.25"
wayland-client = "0.31.7"
wayland-protocols = { version = "0.32.5", features = [ "staging", "client" ] }
zbus = { version = "5.3.1", features = [ "tokio" ] }

[features]
systemd = []
elogind = []
