[package]
name = "moxidle"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
wayland-client = "0.31.7"
wayland-protocols = { version = "0.32.5", features = [ "staging", "client" ] }
